spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dvd_example
    username: dvd_user
    password: dvd
    driver-class-name: org.postgresql.Driver
